services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      # Sobrescribe la ruta del CA con la ruta DENTRO del contenedor
      DB_SSL_CA: /app/backend/ca.pem
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/openapi.json')"]
      interval: 15s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "8080:80"
    depends_on:
      - backend
