version: "3.8"

services:
  backend:
    image: stella101/nexus-backend:${IMAGE_TAG}
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_SSL_CA: /app/backend/ca.pem
    networks: [nexus-net]
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.role == backend]
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  frontend:
    image: stella101/nexus-frontend:${IMAGE_TAG}
    networks: [nexus-net]
    ports:
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.role == frontend]
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  nexus-net:
    driver: overlay
    attachable: true
