name: CI/CD Banco Nexus

on:
  push:
    branches: [proyecto_computo_nube]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push del backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nexus-backend:${{ github.sha }}

      - name: Build y push del frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nexus-frontend:${{ github.sha }}
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

      - name: Desplegar en el Swarm (rolling update)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/banco_nexus
            git pull origin proyecto_computo_nube
            set -a
            source db.env
            set +a
            echo "Desplegando con IMAGE_TAG=${{ github.sha }}"
            IMAGE_TAG=${{ github.sha }} docker stack deploy -c docker-stack.yml nexus --with-registry-auth
